# Generated by Django 3.2 on 2021-05-19 17:20

from django.db import migrations, models
import django.utils.timezone
import util.utils


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone1',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='phone 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='phone 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=util.utils.upload_project_image_path, verbose_name='image'),
        ),
    ]
