# Generated by Django 3.2 on 2021-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210519_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone 2'),
        ),
    ]
