# Generated by Django 3.2 on 2021-06-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-created_at'], 'verbose_name': 'Career', 'verbose_name_plural': 'Career'},
        ),
        migrations.RemoveField(
            model_name='career',
            name='job_position',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_job_position', to='dashboard.jobposition', verbose_name='job position')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='career',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='career_job', to='dashboard.job', verbose_name='job'),
            preserve_default=False,
        ),
    ]
