# Generated by Django 3.2 on 2021-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Internship', 'Internship')], default='Pending', max_length=50, verbose_name='job type'),
        ),
    ]
