# Generated by Django 3.2 on 2021-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hours'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='salary'),
        ),
    ]
