# Generated by Django 3.2 on 2021-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210603_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='contact',
            field=models.CharField(default='12345', max_length=50, verbose_name='contact number'),
            preserve_default=False,
        ),
    ]
