# Generated by Django 3.2 on 2021-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210603_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
