# Generated by Django 3.2 on 2021-06-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_merge_0013_career_contact_0014_alter_jobposition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
