# Generated by Django 3.2 on 2021-06-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_career_file'),
        ('dashboard', '0016_auto_20210607_1310'),
    ]

    operations = [
    ]
