# Generated by Django 3.2 on 2021-06-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_merge_0016_alter_career_file_0016_auto_20210607_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_job', to='dashboard.job', verbose_name='job'),
        ),
    ]
