# Generated by Django 3.2 on 2021-06-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_client_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(default='test-1', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
