# Generated by Django 3.2 on 2021-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_newscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
