# Generated by Django 3.2 on 2021-06-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_newscategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='slug',
        ),
    ]
