# Generated by Django 3.2 on 2021-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_career_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
