# Generated by Django 3.2 on 2021-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_career_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file'),
        ),
    ]
