# Generated by Django 3.2 on 2021-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_career_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
