# Generated by Django 3.2 on 2021-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_newscategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
