# Generated by Django 3.2 on 2021-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_career_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
