# Generated by Django 3.2 on 2021-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_projectcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
