# Generated by Django 3.2 on 2021-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20210627_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='expected_salary',
            field=models.CharField(default='test', max_length=250, verbose_name='expected salary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='passing_year',
            field=models.CharField(default='test', max_length=50, verbose_name='passing year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='subject',
            field=models.CharField(default='test', max_length=250, verbose_name='subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='university_name',
            field=models.CharField(default='test', max_length=100, verbose_name='university name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='year_of_experience',
            field=models.CharField(default='test', max_length=50, verbose_name='year of experience'),
            preserve_default=False,
        ),
    ]
