# Generated by Django 3.2 on 2021-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='is approved'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='is approved'),
        ),
    ]
